const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = 'https://utammtangicjaseucyhd.supabase.co';
const SUPABASE_KEY = 'sb_publishable_VsoaC3k3K4rzPPPJTBNAGw_m8KUh2fF';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

async function initAdminTable() {
    console.log('--- Initializing Admins Table ---');
    try {
        // We can't create tables via standard JS client, 
        // but we can try an insert to see if it works or fails with 404
        const { data, error } = await supabase
            .from('admins')
            .insert([{ username: 'admin', password: 'admin123' }])
            .select();

        if (error) {
            console.error('Error (Expected if table exists/permissions):', error.message);
            if (error.code === '42P01') {
                console.log('Table "admins" does not exist. Please create it in Supabase SQL Editor:');
                console.log('CREATE TABLE admins (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT UNIQUE, password TEXT);');
            }
        } else {
            console.log('Success! Admin created or already exists.', data);
        }
    } catch (err) {
        console.error('Init failed:', err);
    }
}

initAdminTable();
